<div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <form class="reg-page" action="<?php echo $this->url('application',array('controller'=>'user','action'=>'reg'));?>" method="post">
            <div class="reg-header">
                <h2>Register a new account</h2>
                <p>Already Signed Up? Click <a href="page_login.html" class="color-green">Sign In</a> to login your account.</p>
            </div>

            <label>First Name<span class="color-red">*</span></label>
            <input type="text" class="form-control margin-bottom-20" name="username">



            <label>Email Address <span class="color-red">*</span></label>
            <input type="text" class="form-control margin-bottom-20" name="email">

            <div class="row">
                <div class="col-sm-6">
                    <label>Password <span class="color-red">*</span></label>
                    <input type="password" class="form-control margin-bottom-20" name="password">
                </div>
                <div class="col-sm-6">
                    <label>Confirm Password <span class="color-red">*</span></label>
                    <input type="password" class="form-control margin-bottom-20" name="repassword">
                </div>
            </div>

            <hr>

            <div class="row">
                <div class="col-lg-6">
                    <label class="checkbox">
                        <input type="checkbox">
                        I read <a href="page_terms.html" class="color-green">Terms and Conditions</a>
                    </label>
                </div>
                <div class="col-lg-6 text-right">
                    <button class="btn-u" type="submit">Register</button>
                </div>
            </div>
        </form>
    </div>
</div>