
<!-- Service Blocks -->
<div class="row margin-bottom-30">
    <div class="col-md-4">
        <div class="service">
            <i class="fa fa-compress service-icon"></i>
            <div class="desc">
                <h4>Fully Responsive</h4>
                <p>Donec id elit non mi porta gravida at eget
                    metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
                    condimentum nibh, ut fermentum massa justo sit amet risus etiam sem...</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="service">
            <i class="fa fa-cogs service-icon"></i>
            <div class="desc">
                <h4>HTML5 + CSS3</h4>
                <p>Donec id elit non mi porta gravida at eget
                    metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
                    condimentum nibh, ut fermentum massa justo sit amet risus etiam sem...</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="service">
            <i class="fa fa-rocket service-icon"></i>
            <div class="desc">
                <h4>Launch Ready</h4>
                <p>Donec id elit non mi porta gravida at eget
                    metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
                    condimentum nibh, ut fermentum massa justo sit amet risus etiam sem...</p>
            </div>
        </div>
    </div>
</div>
<!-- End Service Blokcs -->

<!-- Recent Works -->
<div class="headline"><h2>Recent Works</h2></div>
<div class="row margin-bottom-20">
    <div class="col-md-3 col-sm-6">
        <div class="thumbnails thumbnail-style thumbnail-kenburn">
            <div class="thumbnail-img">
                <div class="overflow-hidden">
                    <img alt="" src="Unify%20_%20Welcome_files/2.jpg" class="img-responsive">
                </div>
                <a href="#" class="btn-more hover-effect">read more +</a>
            </div>
            <div class="caption">
                <h3><a href="#" class="hover-effect">Project One</a></h3>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem.</p>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="thumbnails thumbnail-style thumbnail-kenburn">
            <div class="thumbnail-img">
                <div class="overflow-hidden">
                    <img alt="" src="Unify%20_%20Welcome_files/3.jpg" class="img-responsive">
                </div>
                <a href="#" class="btn-more hover-effect">read more +</a>
            </div>
            <div class="caption">
                <h3><a href="#" class="hover-effect">Project Two</a></h3>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem.</p>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="thumbnails thumbnail-style thumbnail-kenburn">
            <div class="thumbnail-img">
                <div class="overflow-hidden">
                    <img alt="" src="Unify%20_%20Welcome_files/9.jpg" class="img-responsive">
                </div>
                <a href="#" class="btn-more hover-effect">read more +</a>
            </div>
            <div class="caption">
                <h3><a href="#" class="hover-effect">Project Three</a></h3>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem.</p>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="thumbnails thumbnail-style thumbnail-kenburn">
            <div class="thumbnail-img">
                <div class="overflow-hidden">
                    <img alt="" src="Unify%20_%20Welcome_files/10.jpg" class="img-responsive">
                </div>
                <a href="#" class="btn-more hover-effect">read more +</a>
            </div>
            <div class="caption">
                <h3><a href="#" class="hover-effect">Project Four</a></h3>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, justo sit amet risus etiam porta sem.</p>
            </div>
        </div>
    </div>
</div>
<!-- End Recent Works -->

<!-- Info Blokcs -->
<div class="row margin-bottom-30">
    <!-- Welcome Block -->
    <div class="col-md-8 md-margin-bottom-40">
        <div class="headline"><h2>Welcome To Unify</h2></div>
        <div class="row">
            <div class="col-sm-4">
                <img alt="" src="Unify%20_%20Welcome_files/6_002.jpg" class="img-responsive margin-bottom-20">
            </div>
            <div class="col-sm-8">
                <p>Unify is an incredibly beautiful responsive
                    Bootstrap Template for corporate and creative professionals. It works on
                    all major web browsers, tablets and phone.</p>
                <ul class="list-unstyled margin-bottom-20">
                    <li><i class="fa fa-check color-green"></i> Donec id elit non mi porta gravida</li>
                    <li><i class="fa fa-check color-green"></i> Corporate and Creative</li>
                    <li><i class="fa fa-check color-green"></i> Responsive Bootstrap Template</li>
                    <li><i class="fa fa-check color-green"></i> Corporate and Creative</li>
                </ul>
            </div>
        </div>

        <blockquote class="hero-unify">
            <p>Award winning digital agency. We bring a personal
                and effective approach to every project we work on, which is why. Unify
                is an incredibly beautiful responsive Bootstrap Template for corporate
                professionals.</p>
            <small>CEO, Jack Bour</small>
        </blockquote>
    </div><!--/col-md-8-->

    <!-- Latest Shots -->
    <div class="col-md-4">
        <div class="headline"><h2>Latest Shots</h2></div>
        <div class="carousel slide carousel-v1" id="myCarousel">
            <div class="carousel-inner">
                <div class="item active">
                    <img alt="" src="Unify%20_%20Welcome_files/5.jpg">
                    <div class="carousel-caption">
                        <p>Facilisis odio, dapibus ac justo acilisis gestinas.</p>
                    </div>
                </div>
                <div class="item">
                    <img alt="" src="Unify%20_%20Welcome_files/4.jpg">
                    <div class="carousel-caption">
                        <p>Cras justo odio, dapibus ac facilisis into egestas.</p>
                    </div>
                </div>
                <div class="item">
                    <img alt="" src="Unify%20_%20Welcome_files/3.jpg">
                    <div class="carousel-caption">
                        <p>Justo cras odio apibus ac afilisis lingestas de.</p>
                    </div>
                </div>
            </div>

            <div class="carousel-arrow">
                <a data-slide="prev" href="#myCarousel" class="left carousel-control">
                    <i class="fa fa-angle-left"></i>
                </a>
                <a data-slide="next" href="#myCarousel" class="right carousel-control">
                    <i class="fa fa-angle-right"></i>
                </a>
            </div>
        </div>
    </div><!--/col-md-4-->
</div>
<!-- End Info Blokcs -->

<!-- Our Clients -->
<div class="flexslider home clients" id="clients-flexslider">
    <div class="headline"><h2>Our Clients</h2></div>

    <div class="flex-viewport" style="overflow: hidden; position: relative;"></div><div class="flex-viewport" style="overflow: hidden; position: relative;"><ul class="slides" style="width: 3400%; transition-duration: 0.6s; transform: translate3d(-503.111px, 0px, 0px);">
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/hp_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/hp.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/igneus_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/igneus.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/vadafone_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/vadafone.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/walmart_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/walmart.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/shell_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/shell.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/natural_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/natural.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/aztec_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/aztec.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/gamescast_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/gamescast.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/cisco_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/cisco.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/everyday_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/everyday.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/cocacola_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/cocacola.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/spinworkx_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/spinworkx.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/shell_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/shell.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/natural_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/natural.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/gamescast_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/gamescast.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/everyday_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/everyday.png">
                </a>
            </li>
            <li style="width: 124.778px; float: left; display: block;">
                <a href="#">
                    <img alt="" src="Unify%20_%20Welcome_files/spinworkx_grey.png">
                    <img alt="" class="color-img" src="Unify%20_%20Welcome_files/spinworkx.png">
                </a>
            </li>
        </ul></div></div><!--/flexslider-->
<!-- End Our Clients -->
